name: Auto-fill PR Description from Branch Name

on:
  pull_request:
    types: [opened, synchronize, edited]
    branches:
      - stage
      - master
      - main

permissions:
  pull-requests: write

jobs:
  fill-description:
    runs-on: ubuntu-latest

    steps:
      - name: Install GitHub CLI
        run: |
          echo "🔧 Installing GitHub CLI..."
          sudo apt update
          sudo apt install -y gh

      - name: Authenticate GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "🔑 Authenticating with GitHub CLI..."
          gh auth status

      - name: Generate and Update PR Description
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          echo "📋 Fetching source branch of PR #$PR_NUMBER from $REPO..."
          BRANCH=$(gh pr view "$PR_NUMBER" --repo "$REPO" --json headRefName -q .headRefName)

          echo "🔎 PR Source Branch: $BRANCH"

          declare -A TICKETS_BY_TYPE
          DESCRIPTION=""

          # Match branch pattern: type/#ticket_desc (e.g., feature/#12345_add-login)
          if [[ "$BRANCH" =~ ^(feature|bugfix|improvements|chore)/#([0-9]+)_ ]]; then
            TYPE="${BASH_REMATCH[1]}"
            TICKET="${BASH_REMATCH[2]}"
            echo "✅ Matched branch type: $TYPE"
            echo "🎫 Extracted ticket number: $TICKET"
            TICKETS_BY_TYPE["$TYPE"]="$TICKET"
          else
            echo "⚠️ Branch format does not match expected pattern. Skipping update."
            exit 0
          fi

          # Construct the description
          for TYPE in "${!TICKETS_BY_TYPE[@]}"; do
            DESCRIPTION+="### $TYPE"$'\n'
            DESCRIPTION+="- Kunnusta/tickets#${TICKETS_BY_TYPE[$TYPE]}"$'\n\n'
          done

          echo "📝 Generated PR Description:"
          echo "$DESCRIPTION"

          echo "📤 Updating PR description..."
          gh pr edit "$PR_NUMBER" --repo "$REPO" --body "$DESCRIPTION"
          echo "✅ PR description updated successfully."
